---
title: Outputs
---

Latest update - 29 December, 2022
<br />
<br />

<style>
table, th, td {
    font-size: 100%;
}
</style>

## International Papers
### – In Review/Preparation
| | |
| :- | :---------------- |
| in prep. | <span style="font-weight:bold; color: #06283D; ">Yamada T</span>, Urabe H, & Nakamura F.<br />Determinant factors on the freshwater productivity of anadromous salmonids. |
| in review | <span style="font-weight:bold; color: #06283D; ">Yamada T</span>, Koizumi I, & Nakamura F.<br />Seasonal changes in the ratio of congeneric salmonids in tributaries with different temperature regimes. |

### – Published
| | |
| :- | :---------------- |
| early view | Nakahashi H, <span style="font-weight:bold; color: #06283D; ">Yamada T (joint-first and corresponding author)</span>, Ishiyama N, & Nakamura F.<br />Ecological value of gravel pit ponds for floodplain wetland fish.<br />*Freshwater Biology*. https://doi.org/10.1111/fwb.14029 |
| 2022 | <span style="font-weight:bold; color: #06283D; ">Yamada T</span>, Katahira H, Miura K, & Nakamura F.<br />Relationship between salmon egg subsidy and the distribution of an avian predator. <br />*Ecology and Evolution* 12: e9696. https://doi.org/10.1002/ece3.9696 |
| 2022 | <span style="font-weight:bold; color: #06283D; ">Yamada T</span>, Urabe H, & Nakamura F. <br />Diel migration pattern of pink salmon fry in small streams. <br />*Journal of Fish Biology* 100: 1088–1092. https://doi.org/10.1111/jfb.15007 |
| 2020 | <span style="font-weight:bold; color: #06283D; ">Yamada T</span>, Koizumi I, Urabe H, & Nakamura F. <br />Temperature-dependent swimming performance differs by species: Implications for condition-specific competition between stream salmonids. <br />*Zoological Science* 37: 1–5. https://doi.org/10.2108/zs190149 |
<br />


## Domestic Papers
| | |
| :- | :---------------- |
| 2021 | 三浦一輝, 崎山智樹, 宇久村三世, <span style="font-weight:bold; color: #06283D; ">山田太平</span>. <br />知床半島河川において採集したコガタカワシンジュガイ. <br />斜里町立知床博物館研究報告 43: 1–4. (non-refereed) |
| 2020 | <span style="font-weight:bold; color: #06283D; ">山田太平</span>, 三浦一輝. <br />北海道豊頃町および新得町におけるカワシンジュガイ属（*Margaritifera*）の採集記録. <br />ひがし大雪自然館研究報告 7: 41–45. (non-refereed) |
| 2019 | <span style="font-weight:bold; color: #06283D; ">山田太平</span>, 三浦一輝. <br />北海道十勝地方におけるカワシンジュガイ（*Margaritifera laevis*）とコガタカワシンジュガイ（*M. togakushiensis*）の生息情報. <br />ひがし大雪自然館研究報告 6: 9–12. (non-refereed) |
<br />


## Presentations
| | |
| :- | :---------------- |
| 2022/12 | <span style="font-weight:bold; color: #06283D; ">山田太平</span>, 卜部浩一, 中村太士. <br />流域の地形特性は溯河性サケ科魚類の再生産効率を規定するか？. <br />第15回サケ学研究会, 水産研究・教育機構水産資源研究所, 口頭. |
| 2022/12 | <span style="font-weight:bold; color: #06283D; ">山田太平</span>, 卜部浩一, 中村太士. <br />溯河性サケ科魚類の再生産効率は流域の地形特性によって規定される. <br />第43回魚類系統研究会, 北海道大学大学院環境科学院, 口頭. |
| 2022/10 | <span style="font-weight:bold; color: #06283D; ">Yamada T</span>, Urabe H, Nakamura F. <br />A broad-scale prediction of reduction in spawning habitats for salmonids by dams. <br />IYS Synthesis Symposium, The Westin Bayshore, Vancouver, Canada, Poster. |
| 2022/03 | <span style="font-weight:bold; color: #06283D; ">山田太平</span>, 卜部浩一, 中村太士. <br />ダムによるサケ科魚類の産卵環境減少の広域的予測. <br />日本生態学会第69回全国大会, 福岡国際会議場, ポスター. |
| 2020/03 | <span style="font-weight:bold; color: #06283D; ">山田太平</span>, 小泉逸郎, 中村太士. <br />河川性サケ科魚類の水温依存的な種間競争: 季節変化を考慮した野外検証. <br />日本生態学会第67回全国大会, 名城大学, ポスター. |
| 2018/03 | <span style="font-weight:bold; color: #06283D; ">山田太平</span>, 小泉逸郎, 卜部浩一, 中村太士. <br />河川性魚類の分布規定要因: 遊泳能力と種間競争を考慮した検証. <br />日本生態学会第65回全国大会, 札幌コンベンションセンター, ポスター. |
<br />


## Outreaches
| | |
| :-- | :---------------- |
| 2020/07/04 | 自然観察会: 淡水魚編 (市民向け観察会, 講師). ひがし大雪自然館, 上士幌. |
| 2020/06/30<br />2020/07/02 | 上士幌学: 水生昆虫と水質調査 (高校生向け講義, 講師). 北海道上士幌高等学校, 上士幌. |
| 2019/12/15 | 魚類学: 種同定とスケッチの基礎 (市民向け講座, 講師). ひがし大雪自然館, 上士幌. |
| 2019/07/14 | 自然観察会: 淡水魚編 (市民向け観察会, 講師). ひがし大雪自然館, 上士幌. |





<!-- Google Fonts -->
<link rel="preconnect" href="https://fonts.googleapis.com"> 
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> 
<link href="https://fonts.googleapis.com/css2?family=Josefin+Sans&display=swap" rel="stylesheet">
