---
title: Profile
---

## Biography

山田 太平
<br />
Yamada Taihei
<br />
[`r icon_style(icons::fontawesome("researchgate"), scale = 1, fill = '#5A5A5A')`](https://www.researchgate.net/profile/Taihei-Yamada-2) [`r icon_style(icons::fontawesome("orcid"), scale = 1, fill = '#5A5A5A')`](https://orcid.org/0000-0002-6120-7094) [`r icon_style(icons::fontawesome("instagram"), scale = 1, fill = '#5A5A5A')`](https://www.instagram.com/prbnmt/)

北海道大学大学院農学院 生態系管理学研究室
<br />
Ecosystem Management Group, Graduate School of Agriculture, Hokkaido University

E-mail: thymd8 [at] gmail.com
<br />
<br />

<style>
table, th, td {
    font-size: 100%;
}
</style>

## Education
| | | |
| :-- | :- | :------- |
| 2020.04 – Present | Ph.D. | Grad. Agriculture, Hokkaido Univ., Japan<br />北海道大学大学院 農学院 (指導: 中村太士 教授) |
| 2017.04 – 2019.03 | M.Sc. | Grad. Agriculture, Hokkaido Univ., Japan<br />北海道大学大学院 農学院 |
| 2013.04 – 2017.03 | B.Sc. | Sch. Marine Biosciences, Kitasato Univ., Japan<br />北里大学 海洋生命科学部 |
| 2010.04 – 2013.03 |    | 沖縄県立八重山高等学校 |
<br />
<br />

## Works
| | | |
| :-- | :- | :------- |
| 2018.09 – 2020.08 | Assistant Curator | Higashitaisetsu Museum, Japan<br />上士幌町 商工観光課 ひがし大雪自然館 |
<br />
<br />

## Fellowships and Grants
| | | |
| :-- | :- | :------- |
| 2022.04 – 2024.03 | | JSPS Research Fellow DC2<br />日本学術振興会特別研究員DC2 |
| 2021.10 – 2022.03 | | Hokkaido University DX Doctoral Fellowship<br />北海道大学 DX 博士人材フェローシップ |
<br />
<br />

## Skills
- R

- GIS

- 魚類に関する野外調査全般
<br />
Fish surveys

- 水生昆虫の同定
<br />
Identification of aquatic invertebrates

- 大型自動二輪免許
<br />
Driver's license for large motorcycles



<!-- Google Fonts -->
<link rel="preconnect" href="https://fonts.googleapis.com"> 
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> 
<link href="https://fonts.googleapis.com/css2?family=Josefin+Sans&display=swap" rel="stylesheet">
